# Start the service with the command 'docker-compose up -d'

version: '3.9'

services:
  mongo-bch-consumer:
    image: mongo:4.2.0
    container_name: mongo-bch-consumer
    ports:
      - '5558:27017' # <host port>:<container port>
    volumes:
      - ../data/database:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  ipfs-bch-consumer:
    build: .
    #image: christroutner/ipfs-service-provider:v5.0.1
    container_name: ipfs-bch-consumer
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 1000mb
    links:
      - mongo-bch-consumer
    ports:
      - '5015:5015' # <host port>:<container port>
      - '4101:4101'
      - '4103:4103'
      - '4105:4105'
    volumes:
      - ../data/ipfsdata:/home/safeuser/ipfs-bch-wallet-consumer/.ipfsdata
      - ./start-production.sh:/home/safeuser/ipfs-bch-wallet-consumer/start-production.sh
    restart: always
