# Start the service with the command 'docker-compose up -d'

version: '3.9'

services:
  mongo-bch-consumer:
    image: mongo:4.2.0
    container_name: mongo-bch-consumer
    ports:
      - '5555:27017' # <host port>:<container port>
    volumes:
      - ../data/database:/data/db
    command: mongod --logpath=/dev/null # -- quiet
    restart: always

  ipfs-bch-consumer:
    # https://github.com/christroutner/trickle-ipfs
    image: christroutner/trickle-ipfs:v1.0.1
    #build:
    #  context: ./
    #  dockerfile: Dockerfile
    container_name: ipfs-bch-consumer
    environment:
      IPFS_DAEMON_ARGUMENTS: '--enable-pubsub-experiment --migrate=true --agent-version-suffix=docker --routing=dhtclient'
      UPLOAD_KBPS: '1000'
      DOWNLOAD_KBPS: '1000'
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 2000mb
    ports:
      - 4001:4001
      - 4003:4003
      - 172.17.0.1:5001:5001
      - 172.17.0.1:8080:8080
    command: [
      './start-ipfs.sh'
    ]
    volumes:
      - ../data/go-ipfs/data:/root/.ipfs
    restart: always

  bch-consumer:
    #build: .
    image: christroutner/ipfs-bch-wallet-consumer:v1.8.4
    container_name: bch-consumer
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '10'
    mem_limit: 500mb
    links:
      - mongo-bch-consumer
      - ipfs-bch-consumer
    ports:
      - '5010:5010' # <host port>:<container port>
    volumes:
      - ../data/ipfsdata:/home/safeuser/ipfs-bch-wallet-consumer/.ipfsdata
      - ./start-production.sh:/home/safeuser/ipfs-bch-wallet-consumer/start-production.sh
    restart: always
